import { Company, Restaurant, User } from "@/types/user";

export const demoCompany: Company = {
  id: "tamer-restoran-grubu",
  name: "Tamer Restoran Grubu",
  slug: "tamer-restoran-grubu",
  logo: "",
  phone: "+90 212 555 0123",
  email: "info@tamerrestoran.com",
  address: "İstanbul, Türkiye",
  createdAt: new Date(),
  updatedAt: new Date(),
  isActive: true,
};

export const demoRestaurants: Restaurant[] = [
  {
    id: "tamer-merkez",
    companyId: "tamer-restoran-grubu",
    name: "Tamer Merkez Şube",
    slug: "tamer-merkez",
    address: "Nişantaşı, Teşvikiye Cad. No:45, Şişli/İstanbul",
    phone: "+90 212 555 0124",
    email: "merkez@tamerrestoran.com",
    logo: "",
    settings: {
      timezone: "Europe/Istanbul",
      currency: "TRY",
      openingHours: {
        monday: { open: "11:00", close: "23:00", isClosed: false },
        tuesday: { open: "11:00", close: "23:00", isClosed: false },
        wednesday: { open: "11:00", close: "23:00", isClosed: false },
        thursday: { open: "11:00", close: "23:00", isClosed: false },
        friday: { open: "11:00", close: "24:00", isClosed: false },
        saturday: { open: "11:00", close: "24:00", isClosed: false },
        sunday: { open: "12:00", close: "22:00", isClosed: false },
      },
      tableCapacity: 120,
      reservationSettings: {
        maxAdvanceDays: 30,
        minAdvanceHours: 2,
        slotDuration: 60,
        allowOnlineBooking: true,
      },
    },
    createdAt: new Date(),
    updatedAt: new Date(),
    isActive: true,
  },
  {
    id: "tamer-kadikoy",
    companyId: "tamer-restoran-grubu",
    name: "Tamer Kadıköy Şube",
    slug: "tamer-kadikoy",
    address: "Kadıköy, Moda Cad. No:78, Kadıköy/İstanbul",
    phone: "+90 216 555 0125",
    email: "kadikoy@tamerrestoran.com",
    logo: "",
    settings: {
      timezone: "Europe/Istanbul",
      currency: "TRY",
      openingHours: {
        monday: { open: "11:00", close: "23:00", isClosed: false },
        tuesday: { open: "11:00", close: "23:00", isClosed: false },
        wednesday: { open: "11:00", close: "23:00", isClosed: false },
        thursday: { open: "11:00", close: "23:00", isClosed: false },
        friday: { open: "11:00", close: "24:00", isClosed: false },
        saturday: { open: "11:00", close: "24:00", isClosed: false },
        sunday: { open: "12:00", close: "22:00", isClosed: false },
      },
      tableCapacity: 80,
      reservationSettings: {
        maxAdvanceDays: 30,
        minAdvanceHours: 2,
        slotDuration: 60,
        allowOnlineBooking: true,
      },
    },
    createdAt: new Date(),
    updatedAt: new Date(),
    isActive: true,
  },
  {
    id: "tamer-bebek",
    companyId: "tamer-restoran-grubu",
    name: "Tamer Bebek Şube",
    slug: "tamer-bebek",
    address: "Bebek, Cevdetpaşa Cad. No:92, Beşiktaş/İstanbul",
    phone: "+90 212 555 0126",
    email: "bebek@tamerrestoran.com",
    logo: "",
    settings: {
      timezone: "Europe/Istanbul",
      currency: "TRY",
      openingHours: {
        monday: { open: "11:00", close: "23:00", isClosed: false },
        tuesday: { open: "11:00", close: "23:00", isClosed: false },
        wednesday: { open: "11:00", close: "23:00", isClosed: false },
        thursday: { open: "11:00", close: "23:00", isClosed: false },
        friday: { open: "11:00", close: "24:00", isClosed: false },
        saturday: { open: "11:00", close: "24:00", isClosed: false },
        sunday: { open: "12:00", close: "22:00", isClosed: false },
      },
      tableCapacity: 60,
      reservationSettings: {
        maxAdvanceDays: 30,
        minAdvanceHours: 2,
        slotDuration: 60,
        allowOnlineBooking: true,
      },
    },
    createdAt: new Date(),
    updatedAt: new Date(),
    isActive: true,
  },
];

export const demoUsers: User[] = [
  {
    uid: "super-admin-uid",
    email: "admin@zonekult.com",
    displayName: "Zonekult Admin",
    role: "SUPER_ADMIN",
    permissions: {
      canManageReservations: true,
      canManageTables: true,
      canManageStaff: true,
      canManageSettings: true,
      canViewReports: true,
    },
    createdAt: new Date(),
    updatedAt: new Date(),
    lastLoginAt: new Date(),
    isActive: true,
  },
  {
    uid: "tamer-admin-uid",
    email: "tamer@tamerrestoran.com",
    displayName: "Tamer Bey",
    role: "COMPANY_ADMIN",
    companyId: "tamer-restoran-grubu",
    restaurantIds: ["tamer-merkez", "tamer-kadikoy", "tamer-bebek"],
    permissions: {
      canManageReservations: true,
      canManageTables: true,
      canManageStaff: true,
      canManageSettings: true,
      canViewReports: true,
    },
    createdAt: new Date(),
    updatedAt: new Date(),
    lastLoginAt: new Date(),
    isActive: true,
  },
  {
    uid: "merkez-manager-uid",
    email: "manager.merkez@tamerrestoran.com",
    displayName: "Ahmet Yılmaz",
    role: "RESTAURANT_ADMIN",
    companyId: "tamer-restoran-grubu",
    restaurantIds: ["tamer-merkez"],
    permissions: {
      canManageReservations: true,
      canManageTables: true,
      canManageStaff: false,
      canManageSettings: false,
      canViewReports: true,
    },
    createdAt: new Date(),
    updatedAt: new Date(),
    lastLoginAt: new Date(),
    isActive: true,
  },
  {
    uid: "kadikoy-manager-uid",
    email: "manager.kadikoy@tamerrestoran.com",
    displayName: "Fatma Demir",
    role: "RESTAURANT_ADMIN",
    companyId: "tamer-restoran-grubu",
    restaurantIds: ["tamer-kadikoy"],
    permissions: {
      canManageReservations: true,
      canManageTables: true,
      canManageStaff: false,
      canManageSettings: false,
      canViewReports: true,
    },
    createdAt: new Date(),
    updatedAt: new Date(),
    lastLoginAt: new Date(),
    isActive: true,
  },
  {
    uid: "bebek-manager-uid",
    email: "manager.bebek@tamerrestoran.com",
    displayName: "Mehmet Kaya",
    role: "RESTAURANT_ADMIN",
    companyId: "tamer-restoran-grubu",
    restaurantIds: ["tamer-bebek"],
    permissions: {
      canManageReservations: true,
      canManageTables: true,
      canManageStaff: false,
      canManageSettings: false,
      canViewReports: true,
    },
    createdAt: new Date(),
    updatedAt: new Date(),
    lastLoginAt: new Date(),
    isActive: true,
  },
];

export const demoTableCategories = [
  {
    id: "salon-merkez",
    companyId: "tamer-restoran-grubu",
    restaurantId: "tamer-merkez",
    name: "Ana Salon",
    color: "#3b82f6",
    borderColor: "#1d4ed8",
    backgroundColor: "#dbeafe",
    description: "Ana salon masaları",
    isActive: true,
  },
  {
    id: "terrace-merkez",
    companyId: "tamer-restoran-grubu",
    restaurantId: "tamer-merkez",
    name: "Terrace",
    color: "#10b981",
    borderColor: "#047857",
    backgroundColor: "#d1fae5",
    description: "Terrace masaları",
    isActive: true,
  },
  {
    id: "salon-kadikoy",
    companyId: "tamer-restoran-grubu",
    restaurantId: "tamer-kadikoy",
    name: "Ana Salon",
    color: "#3b82f6",
    borderColor: "#1d4ed8",
    backgroundColor: "#dbeafe",
    description: "Ana salon masaları",
    isActive: true,
  },
  {
    id: "garden-kadikoy",
    companyId: "tamer-restoran-grubu",
    restaurantId: "tamer-kadikoy",
    name: "Bahçe",
    color: "#10b981",
    borderColor: "#047857",
    backgroundColor: "#d1fae5",
    description: "Bahçe masaları",
    isActive: true,
  },
  {
    id: "salon-bebek",
    companyId: "tamer-restoran-grubu",
    restaurantId: "tamer-bebek",
    name: "Ana Salon",
    color: "#3b82f6",
    borderColor: "#1d4ed8",
    backgroundColor: "#dbeafe",
    description: "Ana salon masaları",
    isActive: true,
  },
  {
    id: "vip-bebek",
    companyId: "tamer-restoran-grubu",
    restaurantId: "tamer-bebek",
    name: "VIP Bölüm",
    color: "#f59e0b",
    borderColor: "#d97706",
    backgroundColor: "#fef3c7",
    description: "VIP masalar",
    isActive: true,
  },
];

export const demoTables = [
  // Tamer Merkez Şube masaları
  ...Array.from({ length: 15 }, (_, i) => ({
    id: `merkez-table-${i + 1}`,
    companyId: "tamer-restoran-grubu",
    restaurantId: "tamer-merkez",
    number: i + 1,
    capacity: [2, 4, 6, 8][Math.floor(Math.random() * 4)],
    categoryId: i < 10 ? "salon-merkez" : "terrace-merkez",
    status: "available" as const,
    isActive: true,
  })),

  // Tamer Kadıköy Şube masaları
  ...Array.from({ length: 12 }, (_, i) => ({
    id: `kadikoy-table-${i + 1}`,
    companyId: "tamer-restoran-grubu",
    restaurantId: "tamer-kadikoy",
    number: i + 1,
    capacity: [2, 4, 6][Math.floor(Math.random() * 3)],
    categoryId: i < 8 ? "salon-kadikoy" : "garden-kadikoy",
    status: "available" as const,
    isActive: true,
  })),

  // Tamer Bebek Şube masaları
  ...Array.from({ length: 10 }, (_, i) => ({
    id: `bebek-table-${i + 1}`,
    companyId: "tamer-restoran-grubu",
    restaurantId: "tamer-bebek",
    number: i + 1,
    capacity: [2, 4, 6][Math.floor(Math.random() * 3)],
    categoryId: i < 7 ? "salon-bebek" : "vip-bebek",
    status: "available" as const,
    isActive: true,
  })),
];
