[build]
  command = "NEXT_PUBLIC_NETLIFY_DEPLOYMENT=true npm ci --build-from-source && NODE_ENV=production npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  KV_REST_API_URL = "https://accepted-lemur-14810.upstash.io"
  KV_REST_API_TOKEN = "ATnaAAIjcDFhZDY4NDJkNzk0Nzc0ZjljYWE2ZGMyYzA4OWRiNGQ2NHAxMA"
  KV_REST_API_READ_ONLY_TOKEN = "AjnaAAIgcDHuI5mHbACTCoyRSozumZsLv5ucGs40PZi1LKETQwpo-A"
  NODE_VERSION = "18"
  NODE_ENV = "production"
  NEXT_PUBLIC_SKIP_SSG_ADMIN = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild" 