[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_NETLIFY_DEPLOYMENT = "true"
  NODE_VERSION = "18.20.8"
  NODE_ENV = "production"
  NEXT_PUBLIC_SKIP_SSG_ADMIN = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild" 